services:
  prometheus:
    image: prom/prometheus:v3.7.3
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - /mnt/Wd/Portainer/compose/8/:/configs
    command:
      - "--config.file=/configs/prometheus.yml"
    networks:
      - observability

  loki:
    image: grafana/loki:3.5.8
    restart: unless-stopped
    volumes:
      - loki-data:/loki
      - /mnt/Wd/Portainer/compose/8/:/configs
    command:
      - "-config.file=/configs/loki-config.yml"
    networks:
      - observability

  promtail:
    image: grafana/promtail:3.5.8
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /mnt/Wd/Portainer/compose/8/:/configs
    command:
      - "-config.file=/configs/promtail-config.yml"
    networks:
      - observability

  tempo:
    image: grafana/tempo:main-9e5af99
    restart: unless-stopped
    volumes:
      - tempo-data:/var/tempo
      - /mnt/Wd/Portainer/compose/8/configs:/configs
    command:
      - "-config.file=/configs/tempo-config.yml"
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.140.0
    restart: unless-stopped
    volumes:
      - /mnt/Wd/Portainer/compose/8/configs:/configs
    command:
      - "--config=/configs/otel-collector-config.yml"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    networks:
      - observability

  grafana:
    image: grafana/grafana:12.1.4
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana
    ports:
      - "3000:3000"
    networks:
      - observability

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.3
    restart: unless-stopped
    environment:
      - ASPIRE_DASHBOARD__MODE=External
      - ASPNETCORE_URLS=http://+:18888
    ports:
      - "18888:18888"
    networks:
      - observability

networks:
  observability:
    driver: bridge

volumes:
  prometheus-data:
  loki-data:
  tempo-data:
  grafana-data:
