auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1

ingester:
  chunk_idle_period: 5m
  max_chunk_age: 1h
  lifecycler:
    join_after: 0s
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

distributor:
  ring:
    kvstore:
      store: inmemory

storage_config:
  tsdb:
    dir: /loki/data

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

querier:
  max_concurrent: 2048

query_range:
  parallelise_shardable_queries: true

limits_config:
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_query_parallelism: 32
  max_query_length: 720h

frontend:
  max_outstanding_per_tenant: 2048
