receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s
  probabilistic_sampler:
    sampling_percentage: 100

exporters:
  otlp/tempo:
    endpoint: "tempo:5680"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8989"

  # Use the OTLP HTTP exporter for Loki
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

  otlp/dashboard:
    endpoint: "http://aspire-dashboard:18889"
    tls:
      insecure: true

#  debug: {}
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, probabilistic_sampler]
      exporters: [otlp/tempo, otlp/dashboard]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, otlp/dashboard]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, otlp/dashboard]
