global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8989']
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
  - job_name: 'tempo-usage-metrics'
    metrics_path: '/usage_metrics'
    static_configs:
      - targets: ['tempo:3200']
